# application.yml
# default settings
spring:
    profiles:
                
application:
    name: TextParsedAPI
    baseContext: text-parsed-api-0.1.0
    title: Text Parsed API
    version: 0.1
    
org.rezwan.textparsedapi:
    config:
        topCSVSeparator: "|"
        paragraphFileLocation: TextParagraphDataSource.txt
        restSearchSourceURL : http://localhost:8080/paragraph
        security:
            user: optus
            password: candidates
            roles: USER
            realm: OptusUsers

# This is the Jetty HTTP Server 
server:
    # Jetty HTTP Server Port
    port: 8080
            
---

